// site/src/lib/registry/svelte/flexi-sortable-list/root.svelte
<script lang="ts">
	import type { ComponentProps } from 'svelte';
	import { FlexiSortable } from '@flexiboards/svelte';
	import type { FlexiBoardConfiguration } from '@flexiboards/svelte';
	import { cn } from '$lib/utils.js';
	let {
		class: className,
		config,
		key = 'list',
		direction = 'vertical',
		onreorder,
		controller = $bindable(),
		...props
	}: ComponentProps<typeof FlexiSortable> & { onreorder?: (ids: string[]) => void } = $props();
	const boardConfig = $derived<FlexiBoardConfiguration>({
		...config,
		onLayoutChange: (layout) => {
			config?.onLayoutChange?.(layout);
			onreorder?.(
				[...(layout[key] ?? [])]
					.sort((a, b) =>
						direction === 'vertical' ? (a.y ?? 0) - (b.y ?? 0) : (a.x ?? 0) - (b.x ?? 0)
					)
					.flatMap((entry) => (typeof entry.metadata?.id === 'string' ? [entry.metadata.id] : []))
			);
		}
	});
</script>

<FlexiSortable
	{...props}
	bind:controller
	{key}
	{direction}
	class={cn('gap-2', className)}
	config={boardConfig}
/>

// site/src/lib/registry/react/flexi-sortable-list/root.tsx
'use client';
import { useMemo } from 'react';
import {
	FlexiSortable,
	type FlexiSortableProps,
	type FlexiBoardConfiguration
} from '@flexiboards/react';
import { cn } from '@/lib/utils';
export type RootProps = FlexiSortableProps & { onReorder?: (ids: string[]) => void };
export function Root({
	className,
	config,
	keyName = 'list',
	direction = 'vertical',
	onReorder,
	...props
}: RootProps) {
	const boardConfig = useMemo<FlexiBoardConfiguration>(
		() => ({
			...config,
			onLayoutChange: (layout) => {
				config?.onLayoutChange?.(layout);
				onReorder?.(
					[...(layout[keyName] ?? [])]
						.sort((a, b) =>
							direction === 'vertical' ? (a.y ?? 0) - (b.y ?? 0) : (a.x ?? 0) - (b.x ?? 0)
						)
						.flatMap((entry) => (typeof entry.metadata?.id === 'string' ? [entry.metadata.id] : []))
				);
			}
		}),
		[config, keyName, direction, onReorder]
	);
	return (
		<FlexiSortable
			{...props}
			keyName={keyName}
			direction={direction}
			className={cn('gap-2', className)}
			config={boardConfig}
		/>
	);
}
