// site/src/lib/react-components/examples/flexspressive/brightness-slider.tsx
import { SunMedium } from 'lucide-react';
import { useState } from 'react';

/**
 * A gauge softened into a pill: ink fill in a rounded trough. The Svelte
 * example uses bits-ui's Slider, but the site has no React equivalent, so
 * this is a native range input laid over the same visuals. Same look, same
 * keyboard behaviour, one element fewer.
 */
export default function BrightnessSlider() {
	const [value, setValue] = useState(80);

	return (
		<div className="w-full">
			<div className="relative mb-1.5 mt-2.5 flex w-full touch-none select-none items-center">
				<span className="border-rule-soft bg-tint relative h-[26px] w-full grow cursor-pointer overflow-hidden rounded-full border">
					<span className="bg-ink absolute h-full" style={{ width: `${value}%` }}></span>
					<span className="text-paper absolute left-0 top-0 p-[5px]">
						<SunMedium className="size-4" />
					</span>
				</span>
				<span
					className="bg-fx-accent pointer-events-none absolute block h-9 w-2 rounded-full transition-colors duration-[120ms]"
					style={{ left: `calc(${value}% - ${value * 0.08}px)` }}
				></span>
				<input
					type="range"
					min={0}
					max={100}
					value={value}
					aria-label="Brightness"
					onChange={(event) => setValue(Number(event.target.value))}
					className="focus-visible:outline-hidden absolute inset-0 h-full w-full cursor-pointer opacity-0"
				/>
			</div>
		</div>
	);
}

// site/src/lib/components/examples/flexspressive/brightness-slider.svelte
<script lang="ts">
	import { cn } from "$lib/utils";
    import { Slider } from "bits-ui";
    import SunMedium from "lucide-svelte/icons/sun-medium";

    let value = $state(80);
</script>

<div class="w-full">
    <Slider.Root
        type="single"
        bind:value
        class="relative flex w-full touch-none select-none items-center mt-2.5 mb-1.5"
    >
        <!-- A gauge, softened into a pill: ink fill in a rounded trough. -->
        <span class="relative h-[26px] w-full grow cursor-pointer overflow-hidden rounded-full border border-rule-soft bg-tint">
            <Slider.Range class="bg-ink absolute h-full" />
            <span class="absolute left-0 top-0 text-paper p-[5px]">
                <SunMedium class="size-4" />
            </span>
        </span>
        <Slider.Thumb
        index={0}
        class={cn(
            "focus-visible:ring-fx-accent focus-visible:outline-hidden block h-9 w-2 rounded-full cursor-pointer bg-fx-accent transition-colors duration-[120ms] focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
        )}
        />
    </Slider.Root>
</div>
