// site/src/lib/components/examples/flexion/flexion-quote-block.svelte
<script lang="ts">
	let { label, content }: { label?: string; content?: string } = $props();
</script>

<!-- A note callout: 2px blue rule, tinted ground, softly rounded, never italic. -->
<blockquote
	class="max-w-[68ch] rounded-[10px] border-l-2 border-blue bg-tint px-4 py-3 text-[13px] leading-relaxed text-body lg:text-[13.5px]"
>
	{#if label}<strong class="text-ink">{label}</strong>{/if}
	{content}
</blockquote>

// site/src/lib/react-components/examples/flexion/flexion-quote-block.tsx
/** A note callout: 2px blue rule, tinted ground, softly rounded, never italic. */
export function FlexionQuoteBlock({ label, content }: { label?: string; content?: string }) {
	return (
		<blockquote className="border-blue bg-tint text-body max-w-[68ch] rounded-[10px] border-l-2 px-4 py-3 text-[13px] leading-relaxed lg:text-[13.5px]">
			{label && <strong className="text-ink">{label}</strong>} {content}
		</blockquote>
	);
}

export default FlexionQuoteBlock;
