// site/src/lib/registry/svelte/flexi-handles/grabber.svelte
<script lang="ts">
	import { FlexiGrab } from '@flexiboards/svelte';
	import { cn } from '$lib/utils.js';
	import GripVertical from '@lucide/svelte/icons/grip-vertical';

	let { class: className, size = 16 }: { class?: string; size?: number } = $props();
</script>

<FlexiGrab
	class={cn(
		'text-muted-foreground hover:bg-accent hover:text-accent-foreground shrink-0 rounded-md p-1.5 transition-colors',
		className
	)}
>
	<GripVertical {size} />
</FlexiGrab>

// site/src/lib/registry/react/flexi-handles/grabber.tsx
import { FlexiGrab } from '@flexiboards/react';
import { GripVertical } from 'lucide-react';
import { cn } from '@/lib/utils';

export function Grabber({ className, size = 16 }: { className?: string; size?: number }) {
	return (
		<FlexiGrab
			className={cn(
				'text-muted-foreground hover:bg-accent hover:text-accent-foreground shrink-0 rounded-md p-1.5 transition-colors',
				className
			)}
		>
			<GripVertical size={size} />
		</FlexiGrab>
	);
}
