// site/src/lib/registry/react/flexi-board/root.tsx
'use client';
import { FlexiBoard, type FlexiBoardProps } from '@flexiboards/react';
import { cn } from '@/lib/utils';
export type RootProps = FlexiBoardProps;
export function Root({ className, config, ...props }: RootProps) {
	return (
		<FlexiBoard
			{...props}
			className={cn('text-foreground', className)}
			config={{ ...config, widgetDefaults: { draggability: 'full', ...config?.widgetDefaults } }}
		/>
	);
}

// site/src/lib/registry/svelte/flexi-board/root.svelte
<script lang="ts">
	import type { ComponentProps } from 'svelte';
	import { FlexiBoard } from '@flexiboards/svelte';
	import { cn } from '$lib/utils.js';
	let {
		class: className,
		config,
		controller = $bindable(),
		...props
	}: ComponentProps<typeof FlexiBoard> = $props();
</script>

<FlexiBoard
	{...props}
	bind:controller
	class={cn('text-foreground', className)}
	config={{ ...config, widgetDefaults: { draggability: 'full', ...config?.widgetDefaults } }}
/>
