// packages/svelte-flexiboards/src/lib/components/flexi-target.svelte
<script module lang="ts">
	import type { Snippet } from 'svelte';
	import {
		flexitarget,
		type FlexiTargetConfiguration,
		type FlexiTargetController,
		type FlexiTargetPartialConfiguration
	} from '$lib/system/target.svelte.js';
	import type { FlexiCommonProps } from '$lib/system/types.js';

	export type FlexiTargetProps = FlexiCommonProps<FlexiTargetController> & {
		/**
		 * The header content of the target, above the grid.
		 */
		header?: Snippet<[{ target: FlexiTargetController }]>;

		/**
		 * The child content of the target, which should contain inner FlexiWidget
		 * definitions.
		 */
		children?: Snippet;

		/**
		 * The footer content of the target, below the grid.
		 */
		footer?: Snippet<[{ target: FlexiTargetController }]>;

		/**
		 * The class names to apply to the target's container element.
		 */
		containerClass?: string;

		/**
		 * The class names to apply to the target's grid element.
		 */
		class?: string;

		/**
		 * The configuration object for the target.
		 */
		config?: FlexiTargetPartialConfiguration;

		/**
		 * The unique identifier for the target.
		 * Used to identify the target when layouts are imported or exported.
		 */
		key?: string;
	};
</script>

<script lang="ts">
	import FlexiGrid from './flexi-grid.svelte';
	import FlexiTargetLoader from './flexi-target-loader.svelte';
	import RenderedFlexiWidget from './rendered-flexi-widget.svelte';

	let {
		children,
		class: className,
		header,
		footer,
		config,
		containerClass,
		controller = $bindable(),
		key,
		onfirstcreate
	}: FlexiTargetProps = $props();

	const { onpointerenter, onpointerleave, target } = flexitarget(config, key);

	// Target created, allow the caller to access it.
	controller = target;
	onfirstcreate?.(target);
</script>

<div class={containerClass} {onpointerenter} {onpointerleave} role="grid" tabindex={0}>
	{@render header?.({ target })}

	<!-- Allow user to specify components directly via a registration component. Once that's done, mount them to the actual target list dynamically -->
	<FlexiGrid class={className}>
		{#if !target.prepared && children}
			{@render children()}
		{:else if target.prepared}
			{#each target.widgets as widget (widget)}
				<RenderedFlexiWidget {widget} />
			{/each}
		{/if}
	</FlexiGrid>
	{@render footer?.({ target })}
</div>

<FlexiTargetLoader />

// packages/react/src/components/flexi-target.tsx
import { type FlexiCommonProps, type FlexiTargetController, type FlexiTargetPartialConfiguration } from '@flexiboards/core';
import { useCallback, useEffect, type ReactNode } from 'react';
import { useInternalFlexiBoard } from '../adapters/board.js';
import { FlexiTargetContext } from '../adapters/target.js';
import { useOnce, useSingleRef } from '../adapters/utils.js';
import { useFromCore } from '../adapter.js';
import { RenderedFlexiWidget } from './rendered-flexi-widget.js';
import { FlexiGrid } from './flexi-grid.js';
import { FlexiTargetLoader } from './flexi-target-loader.js';

export type FlexiTargetProps = FlexiCommonProps<FlexiTargetController> & {
	/**
	 * The header content of the target, above the grid.
	 */
	header?: (params: { target: FlexiTargetController}) => ReactNode;

	/**
	 * The child content of the target, which should contain inner FlexiWidget
	 * definitions.
	 */
	children?: ReactNode;

	/**
	 * The footer content of the target, below the grid.
	 */
	footer?: (params: { target: FlexiTargetController}) => ReactNode;

	/**
	 * The class names to apply to the target's container element.
	 */
	containerClassName?: string;

	/**
	 * The class names to apply to the target's grid element.
	 */
	className?: string;

	/**
	 * The configuration object for the target.
	 */
	config?: FlexiTargetPartialConfiguration<string>;

	/**
	 * The unique identifier for the target.
	 * Used to identify the target when layouts are imported or exported.
	 */
	keyName?: string;
};

/**
 * Creates a new FlexiTarget in the context of the current FlexiBoard.
 */
export function FlexiTarget({ children, className, header, footer, config, containerClassName, keyName, onfirstcreate }: FlexiTargetProps) {
	const provider = useInternalFlexiBoard();
	const target = useSingleRef(() => provider.createTarget(config, keyName));

	useOnce(() => onfirstcreate?.(target as FlexiTargetController))

	// Prop seam — see FlexiBoard. Inert unless `config` actually changed.
	useEffect(() => {
		target.updateConfig(config);
	}, [target, config]);

	// Bridge core-signal reads into React's reactivity.
	const prepared = useFromCore(useCallback(() => target.prepared, [target]));
	const orderedWidgets = useFromCore(useCallback(() => target.orderedWidgets, [target]));
	const dropzoneWidget = useFromCore(useCallback(() => target.dropzoneWidget, [target]));
	const shouldRenderDropzoneWidget = useFromCore(useCallback(() => target.shouldRenderDropzoneWidget, [target]));

	return <FlexiTargetContext.Provider value={target}>
		<div className={containerClassName}>
			{header?.({ target: target as FlexiTargetController })}
			
			<FlexiGrid className={className}>
				{children && (
					<div style={prepared ? { visibility: 'hidden' } : {}}>
						{children}
					</div>
				)}

				{prepared && <>
					{orderedWidgets.map((widget) => (
						<RenderedFlexiWidget key={widget.id} widget={widget} />
					))}

					{dropzoneWidget && shouldRenderDropzoneWidget && (
						<RenderedFlexiWidget widget={dropzoneWidget} />
					)}
				</>}
			</FlexiGrid>

			{footer?.({ target: target as FlexiTargetController })}
		</div>

		<FlexiTargetLoader />
	</FlexiTargetContext.Provider>;
}
