// packages/svelte/src/components/flexi-widget.svelte
<script module lang="ts">
	import type {
		FlexiCommonProps,
		FlexiWidgetChildrenSnippet,
		FlexiWidgetClasses,
		FlexiWidgetConfiguration,
		FlexiWidgetController,
		InternalFlexiWidgetController
	} from '@flexiboards/core';
	import { flexiwidget } from '../adapters/widget.js';
	import { reactive } from '../adapter.svelte.js';
	import type { ClassValue } from 'svelte/elements';

	export type FlexiWidgetProps = FlexiCommonProps<FlexiWidgetController> &
		Omit<FlexiWidgetConfiguration<ClassValue>, 'className' | 'snippet'> & {
			/**
			 * The class names to apply to this widget. Either a class value, or a
			 * function deriving one from the widget's state.
			 */
			class?: FlexiWidgetClasses<ClassValue>;

			/**
			 * The content rendered within the widget.
			 */
			children?: FlexiWidgetChildrenSnippet;
		};
</script>

<script lang="ts">
	let {
		class: className = $bindable(),
		children = $bindable(),
		controller = $bindable(),
		onfirstcreate,
		...propsConfig
	}: FlexiWidgetProps = $props();

	let config: FlexiWidgetConfiguration<ClassValue> = $state({
		...propsConfig,
		...(className !== undefined && { className }),
		...(children !== undefined && { snippet: children })
	});

	// The widget is created lazily by the target, so hold the controller in state
	// and let the prop seam below run once it exists. The target always creates
	// internal controllers, and updateConfig lives on the internal type.
	let createdWidget: InternalFlexiWidgetController | undefined = $state();

	// Fulfils the controller and onfirstcreate props once the widget exists.
	function onWidgetCreated(widget: FlexiWidgetController) {
		createdWidget = widget as InternalFlexiWidgetController;

		const publicWidget = reactive(widget);
		controller = publicWidget;
		onfirstcreate?.(publicWidget);
	}

	flexiwidget(config, onWidgetCreated);

	// Prop seam, see FlexiBoard. updateConfig() merges only the keys that
	// changed, so this neither clobbers state set imperatively on the controller
	// nor writes anything when the props are unchanged.
	//
	// Snippets and inline functions are safe to compare by identity here,
	// because a component's setup runs once, so `{#snippet}` declarations and
	// inline arrows are stable consts. A snippet's contents were already
	// reactive on their own, since it closes over the consumer's state. What
	// this adds is propagation when the consumer swaps in a structurally
	// different snippet or class.
	$effect(() => {
		createdWidget?.updateConfig({
			...propsConfig,
			...(className !== undefined && { className }),
			...(children !== undefined && { snippet: children })
		});
	});
</script>

// packages/react/src/components/flexi-widget.tsx
import type {
	FlexiCommonProps,
	FlexiWidgetClasses,
	FlexiWidgetConfiguration,
	FlexiWidgetController,
	InternalFlexiWidgetController
} from '@flexiboards/core';
import { useEffect, useState } from 'react';
import { useFlexiWidgetInit, type FlexiWidgetChildren } from '../adapters/widget.js';

export type FlexiWidgetProps = FlexiCommonProps<FlexiWidgetController> &
	Omit<FlexiWidgetConfiguration<string>, 'className' | 'snippet'> & {
		/**
		 * The class names to apply to this widget. Either a class value, or a
		 * function deriving one from the widget's state.
		 */
		className?: FlexiWidgetClasses<string>;

		/**
		 * The content rendered within the widget.
		 */
		children?: FlexiWidgetChildren;
	};

/**
 * Registers a widget with the surrounding FlexiTarget. Renders nothing itself —
 * the target renders the created widget via RenderedFlexiWidget.
 */
export function FlexiWidget({
	className,
	children,
	onfirstcreate,
	// controller is a Svelte-bindable with no React equivalent; keep it out of
	// the config forwarded to core.
	controller: _controller,
	...propsConfig
}: FlexiWidgetProps) {
	// The widget is created lazily by the target, so hold the controller in state
	// and let the prop seam below run once it exists. The target always creates
	// internal controllers; updateConfig lives on the internal type.
	const [createdWidget, setCreatedWidget] = useState<InternalFlexiWidgetController | undefined>(
		undefined
	);

	const assembleConfig = (): FlexiWidgetConfiguration<string> => ({
		...propsConfig,
		...(className !== undefined && { className }),
		...(children !== undefined && { snippet: children })
	});

	// Callback so that we still fulfil these props.
	function onWidgetCreated(widget: FlexiWidgetController) {
		setCreatedWidget(widget as InternalFlexiWidgetController);

		onfirstcreate?.(widget);
	}

	useFlexiWidgetInit(assembleConfig(), onWidgetCreated);

	// Prop seam — see FlexiBoard. updateConfig() merges only the keys that
	// actually changed, so it never clobbers state set imperatively on the
	// controller and writes nothing when a key is unchanged.
	//
	// Deliberately NO dependency array: unlike Svelte (where snippets and inline
	// functions are stable consts because a component's setup runs once), React
	// rebuilds `children` and inline class functions on every parent render —
	// each render's values are genuinely the current content, so the seam must
	// observe every render. Identity-changed keys (like a fresh children tree)
	// being re-written each time is the semantically correct React behaviour.
	useEffect(() => {
		createdWidget?.updateConfig(assembleConfig());
	});

	return null;
}
