// packages/svelte/src/components/flexi-delete.svelte
<script module lang="ts">
	import {
		assistiveTextStyle,
		type FlexiCommonProps,
		type FlexiDeleteClasses,
		type FlexiDeleteController
	} from '@flexiboards/core';
	import type { Snippet } from 'svelte';
	import { flexidelete } from '../adapters/misc.js';
	import { fromCore, reactive } from '../adapter.svelte.js';
	import type { ClassValue } from 'svelte/elements';

	export type FlexiDeleteProps = FlexiCommonProps<FlexiDeleteController> & {
		/**
		 * The class names to apply to the deleter's container element. Either a
		 * class value, or a function deriving one from the deleter's state.
		 */
		class?: FlexiDeleteClasses<ClassValue>;

		/**
		 * The content rendered inside of the deleter.
		 */
		children?: Snippet<[{ deleter: FlexiDeleteController }]>;
	};
</script>

<script lang="ts">
	let {
		class: className,
		children,
		controller = $bindable(),
		onfirstcreate
	}: FlexiDeleteProps = $props();

	const { deleter } = flexidelete();
	const publicDeleter = reactive(deleter);
	controller = publicDeleter;
	onfirstcreate?.(publicDeleter);

	// fromCore, because the class function may read signal-backed deleter state.
	let derivedClassName = $derived.by(
		fromCore(() => {
			if (typeof className === 'function') {
				return className(deleter);
			}

			return className;
		})
	);

	const assistiveTextId = $props.id();
</script>

<div
	role="region"
	bind:this={deleter.ref}
	class={derivedClassName}
	aria-describedby={assistiveTextId}
>
	<span style={assistiveTextStyle} id={assistiveTextId}>
		Drag a widget here and press Enter to delete it.
	</span>
	{@render children?.({ deleter: publicDeleter })}
</div>

// packages/react/src/components/flexi-delete.tsx
import {
	assistiveTextStyleObject,
	FlexiDeleteController,
	type FlexiDeleteClasses
} from '@flexiboards/core';
import { useCallback, useId } from 'react';
import { useInternalFlexiBoard } from '../adapters/board.js';
import { FlexiDeleteContext } from '../adapters/misc.js';
import {
	controllerRef,
	renderChildren,
	useOnceCommitted,
	useSingleRef,
	type FlexiChildren,
	type FlexiCommonProps
} from '../adapters/utils.js';
import { useFromCore } from '../adapter.js';
import { useReactive } from '../adapters/reactive.js';

export type FlexiDeleteProps = FlexiCommonProps<FlexiDeleteController> & {
	/**
	 * The class names to apply to the deleter's container element. Either a
	 * class value, or a function deriving one from the deleter's state.
	 */
	className?: FlexiDeleteClasses<string>;

	/**
	 * The child content of the deleter, containing the contents of the deleter
	 * button.
	 */
	children?: FlexiChildren<{ deleter: FlexiDeleteController }>;
};

export function FlexiDelete({ children, className, onfirstcreate }: FlexiDeleteProps) {
	const provider = useInternalFlexiBoard();
	const deleter = useSingleRef(() => new FlexiDeleteController(provider));
	useOnceCommitted(() => onfirstcreate?.(deleter));
	const assistiveTextId = useId();
	const publicDeleter = useReactive(deleter);

	// useFromCore, because the class function may read signal-backed deleter state.
	const derivedClassName = useFromCore(
		useCallback(() => {
			if (typeof className === 'function') {
				return className(deleter);
			}
			return className;
		}, [deleter, className])
	);

	return (
		<FlexiDeleteContext.Provider value={deleter}>
			<div
				role="region"
				ref={controllerRef(deleter)}
				className={derivedClassName}
				aria-describedby={assistiveTextId}
			>
				<span style={assistiveTextStyleObject} id={assistiveTextId}>
					Drag a widget here and press Enter to delete it.
				</span>
				{renderChildren(children, { deleter: publicDeleter })}
			</div>
		</FlexiDeleteContext.Provider>
	);
}
