// site/src/lib/components/examples/numbers/number-tile.svelte
<script module lang="ts">
	export type NumberTileProps = {
		number: number;
	};
</script>

<script lang="ts">
	let { number }: NumberTileProps = $props();
</script>

<!-- Numbers are mono, always. Placed widgets get a soft blue rule on tint. -->
<div
	class="flex h-full items-center justify-center rounded-[10px] border border-blue/30 bg-tint p-4 font-mono text-2xl text-blue"
>
	{number}
</div>

// site/src/lib/react-components/examples/numbers/number-tile.tsx
export type NumberTileProps = {
    number: number;
};

export function NumberTile({ number }: NumberTileProps) {
    // Numbers are mono, always. Placed widgets get a soft blue rule on tint.
    return <div
        className="flex h-full items-center justify-center rounded-[10px] border border-blue/30 bg-tint p-4 font-mono text-2xl text-blue"
    >
        {number}
    </div>;
}
