// packages/react/src/components/responsive-flexi-board.tsx
import {
	InternalResponsiveFlexiBoardController,
	type ResponsiveFlexiBoardController,
	type ResponsiveFlexiBoardProps as ResponsiveFlexiBoardPropsPrimitive
} from '@flexiboards/core';
import { Fragment, useCallback, useEffect, type ReactNode } from 'react';
import { ResponsiveFlexiBoardContext } from '../adapters/responsive.js';
import { useOnce, useSingleRef } from '../adapters/utils.js';
import { useFromCore } from '../adapter.js';

export type BreakpointSnippetParams = { currentBreakpoint: string };

export type ResponsiveFlexiBoardProps = ResponsiveFlexiBoardPropsPrimitive & {
	/**
	 * Production for large breakpoint (no params - breakpoint is implicit).
	 */
	lg?: ReactNode;

	/**
	 * Production for medium breakpoint (no params - breakpoint is implicit).
	 */
	md?: ReactNode;

	/**
	 * Production for small breakpoint (no params - breakpoint is implicit).
	 */
	sm?: ReactNode;
	/**
	 * 
	 * Production for extra-small breakpoint (no params - breakpoint is implicit).
	 */
	xs?: ReactNode;

	/**
	 * Children snippet used as fallback when no specific breakpoint snippet matches.
	 * Receives `{ currentBreakpoint: string }` as a parameter.
	 */
	children?: ( params: { currentBreakpoint: string }) => ReactNode;
};

export function ResponsiveFlexiBoard({
	lg,
	md,
	sm,
	xs,
	children,
	config,
	onfirstcreate
}: ResponsiveFlexiBoardProps) {
	const board = useSingleRef(() => {
		// Core's contract is just { config } — adapter-level props stay out.
		const b = new InternalResponsiveFlexiBoardController({ config });
		b.oninitialloadcomplete();

		return b;
	});

	useOnce(() => onfirstcreate?.(board as ResponsiveFlexiBoardController));

	const productions: Record<string, ReactNode | undefined> = { lg, md, sm, xs };

	const currentBreakpoint = useFromCore(useCallback(() => board.currentBreakpoint, [board]));
	const active = productions[currentBreakpoint];

	// Update props when board or config changes.
	useEffect(() => {
		board.updateProps({ config });
	}, [board, config]);

	return (
		<ResponsiveFlexiBoardContext.Provider value={board}>
			<Fragment key={currentBreakpoint}>
				{active !== undefined ? active : children?.({ currentBreakpoint })}
			</Fragment>
		</ResponsiveFlexiBoardContext.Provider>
	);
}

// packages/svelte-flexiboards/src/lib/components/responsive-flexi-board.svelte
<script module lang="ts">
	import { onDestroy, type Snippet } from 'svelte';
	import type { FlexiCommonProps } from '$lib/system/types.js';
	import type { ResponsiveFlexiBoardController } from '$lib/system/responsive/base.svelte.js';
	import type { ResponsiveFlexiBoardConfiguration } from '$lib/system/responsive/types.js';

	export type BreakpointSnippetParams = { currentBreakpoint: string };

	export type ResponsiveFlexiBoardProps = FlexiCommonProps<ResponsiveFlexiBoardController> & {
		config?: ResponsiveFlexiBoardConfiguration;
		/**
		 * Snippet for large breakpoint (no params - breakpoint is implicit).
		 */
		lg?: Snippet;
		/**
		 * Snippet for medium breakpoint (no params - breakpoint is implicit).
		 */
		md?: Snippet;
		/**
		 * Snippet for small breakpoint (no params - breakpoint is implicit).
		 */
		sm?: Snippet;
		/**
		 * Snippet for extra-small breakpoint (no params - breakpoint is implicit).
		 */
		xs?: Snippet;
		/**
		 * Children snippet used as fallback when no specific breakpoint snippet matches.
		 * Receives `{ currentBreakpoint: string }` as a parameter.
		 */
		children?: Snippet<[BreakpointSnippetParams]>;
	};
</script>

<script lang="ts">
	import { responsiveflexiboard } from '$lib/system/responsive/index.js';

	let {
		controller = $bindable(),
		onfirstcreate,
		config,
		lg,
		md,
		sm,
		xs,
		children
	}: ResponsiveFlexiBoardProps = $props();

	const board = responsiveflexiboard({ config });
	controller = board;

	// Load layouts immediately so child FlexiBoards can access them
	board.oninitialloadcomplete();

	onfirstcreate?.(board);

	// Map breakpoint names to snippets (without params)
	const snippets: Record<string, Snippet | undefined> = $derived({
		lg,
		md,
		sm,
		xs
	});

	// Cleanup when component is destroyed
	onDestroy(() => {
		board.destroy();
	});
</script>

<!--
	Key on currentBreakpoint to force re-render when breakpoint changes.
	This ensures the board is re-created with the correct breakpoint context.
-->
{#key board.currentBreakpoint}
	{#if snippets[board.currentBreakpoint]}
		<!-- Specific breakpoint snippet (no params) -->
		{@render snippets[board.currentBreakpoint]!()}
	{:else if children}
		<!-- Children snippet receives { currentBreakpoint } -->
		{@render children({ currentBreakpoint: board.currentBreakpoint })}
	{/if}
{/key}
