// site/src/lib/components/examples/flexspressive/tile.svelte
<script module lang="ts">
	import type { Icon } from 'lucide-svelte';
	import { FlexiWidget, type FlexiWidgetProps } from '@flexiboards/svelte';
	import TileContents from './tile-contents.svelte';

	export type TileProps = FlexiWidgetProps & {
		title: string;
		on: boolean;
		onIcon?: typeof Icon;
		offIcon?: typeof Icon;
	};
</script>

<script lang="ts">
	let { title, on = $bindable(), onIcon: OnIcon, offIcon: OffIcon, ...props }: TileProps = $props();
</script>

<FlexiWidget
	{...props}
	draggability={'none'}
	resizability={'none'}
	maxWidth={2}
	maxHeight={1}
	component={TileContents}
	componentProps={{
		title,
		on,
		onIcon: OnIcon,
		offIcon: OffIcon
	}}
/>

// site/src/lib/react-components/examples/flexspressive/tile.tsx
import { FlexiWidget } from '@flexiboards/react';
import type { FlexiWidgetProps } from '@flexiboards/react';
import type { LucideIcon } from 'lucide-react';
import TileContents from './tile-contents';

export type TileProps = Omit<FlexiWidgetProps, 'children'> & {
	title: string;
	on: boolean;
	onIcon?: LucideIcon;
	offIcon?: LucideIcon;
};

export default function Tile({ title, on, onIcon, offIcon, ...props }: TileProps) {
	return (
		<FlexiWidget
			{...props}
			draggability="none"
			resizability="none"
			maxWidth={2}
			maxHeight={1}
			component={TileContents}
			componentProps={{
				title,
				on,
				onIcon,
				offIcon
			}}
		/>
	);
}
