// site/src/lib/react-components/examples/gallery/plate-artwork.tsx
import { plateStyle } from './plates';
import type { Motif } from './plates';

export type PlateArtworkProps = {
	motif: Motif;
	pair: number;
};

/** The print itself: gradients only, no images and no assets. */
export default function PlateArtwork({ motif, pair }: PlateArtworkProps) {
	return <div className="h-full w-full" style={plateStyle(motif, pair)} aria-hidden="true"></div>;
}

// site/src/lib/components/examples/gallery/plate-artwork.svelte
<script module lang="ts">
	import type { Motif } from './plates.js';

	export type PlateArtworkProps = {
		motif: Motif;
		pair: number;
	};
</script>

<script lang="ts">
	import { plateStyle } from './plates.js';

	let { motif, pair }: PlateArtworkProps = $props();

	const style = $derived(plateStyle(motif, pair));
</script>

<!-- The print itself: gradients only, no images and no assets. -->
<div class="h-full w-full" {style} aria-hidden="true"></div>
